[build]
builder = "NIXPACKS"
buildCommand = "dotnet restore && dotnet publish -c Release -o out"

[deploy]
startCommand = "cd out && dotnet MillionBackend.API.dll"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"
